### ISSUE TITLE
Add container level

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/latex-template#44]
Our sectioning macros are

- Part of a tutoriel,
- Chapter of a tutorial,
- Section of a tutorial,
- `#` title,
- `##` title,
- `###` title,
- `####` title.

But, I think we could distinguish container level and title level, to have the same title macros for any type of document (maybe easier for `rebber`) and to have better introductions macros (see #29). @pierre-24 @AmarOk1412 @vhf ?

**Comment by pierre-24** [comment]
From what I know from the process of turning a content to a PDF (I coded part of it back in ZEP-12), we extend the full text into a single markdown file (with [this template](https://raw.githubusercontent.com/zestedesavoir/zds-site/dev/templates/tutorialv2/export/content.md)), in which the title are "decaled" (it is not English, but that's how the command is called ^^) according to the size of the tutorial, so it matches the current implementation (for example, for article, section titles becomes `#`, and `#` titles becomes `##` and so all).

Therefore, if we keep this behaviour, I don't think we need to change that since this big md file would then be used by rebber to get a PDF file, in l my mind, and rebber can simply use the number of `#` to replace by the corresponding `\LevelxxxTitle`. That was basically the whole point of #6 :)

But of course, if we want to do something else, then your idea may become interesting. So it is up to @vhf to decide whether the pdf will be generated from this "big md file" or something else.

**Comment by pierre-24** [comment]
It may also be interesting to have an input from the other ZEP-12 historical coder. I therefore summon @artragis !

**Comment by artragis** [comment]
Hello,
So what do we do when we publish the tutorial?

First we create the html representation of each container. All titles are shifted (for you pierre) of two levels.

Then we "flatten" the whole markdown and store it in a simple md file. This md file is the very basis for every compilation we provide. 

Latex generation will therefore be handled from a "non shifted" basis and you will really have the chapter/part/subpart artchitecture you're custom with.

**Comment by pierre-24** [comment]
> Latex generation will therefore be handled from a "non shifted" basis and you will really have the chapter/part/subpart artchitecture you're custom with.

This last part seems in opposition to what you explain previously o_O

**Comment by Karnaj** [comment]
Here are the two solutions.

- `\LevelOneTitle` for `# Title`, `\LevelTwoTitle` for `## Title`, etc. `\part`, `\chapter` and `\section` or `LevelOneContainer`, `\LevelTwoContainer` and `\LevelThreeContainer`. 
- `\LevelOneTitle` for : tutorial part if big tutorial, chapter if middle tutorial, section if small tutorial. 

The two are easy to set up. We just have to choose.

**Comment by artragis** [comment]
WHat I call "non shifted" is just a "normal heading hierarchy". eg : 

```markdown

# Tutorial title

## Part One title

### Chapter one title

#### extract title

##### extract sub part title

conten
content

content

## Part two

etc.
```

**Comment by pierre-24** [comment]
Ok. So like I said, the number of `#` is directly related to the level of title, and the template deals with what it mean with the small/medium/big. But if you prefer the solution of @Karnaj, no problem. Just pick what is easier for implementation :)

**Comment by vhf** [comment]
It doesn't matter to us:

* we already have all it takes to shift all titles up or down an arbitrary number of levels
* we already have the compilation from markdown titles to latex.

If you're still ok with [this](https://github.com/zestedesavoir/zmarkdown/blob/12d53a3ff8e2fa82269c6598f4c60d16498bd044/packages/rebber/__tests__/fixtures/heading-config.expected.tex) syntax, let's settle on it.

**Comment by pierre-24** [comment]
I am :)
