### ISSUE TITLE
Investigate tectonic

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/latex-template#46]
Tectonic might be a viable, cleaner alternative to our current latex installation and compilation setup.

https://tectonic-typesetting.github.io

Here is an excerpt of their homepage, emphasis is mine and underlines why I think using it might make sense / be easier/cleaner/better for ZdS:

* Tectonic automatically downloads support files so you don’t have to install a full LaTeX system in order to start using it. If you start using a new LaTeX package, Tectonic just pulls down the files it needs and continues processing. The underyling “bundle” technology allows for **completely reproducible document compiles**. Thanks to JFrog Bintray for hosting the large LaTeX resource files!
* Tectonic has sophisticated logic and automatically loops TeX and BibTeX as needed, and only as much as needed. In its default mode **it doesn’t write TeX’s intermediate files** and always produces a fully-processed document.
* The tectonic command-line program is **quiet and never stops to ask for input**.
* Thanks to the power of XeTeX, Tectonic can use **modern OpenType fonts** and is **fully Unicode-enabled**.
* The Tectonic engine has been extracted into a **completely self-contained** library so that it can be embedded in other applications.

**Comment by lethom** [comment]
I tried the tool this morning.

1. It is very easy to install because it is published on [crates.io](https://crates.io). If you have cabal/rustc installed, it is as easy as `cargo install tectonic` and `alias tectonic=~/.cargo/bin/tectonic` (`cargo install tectonic --force` to update).
2. You do not need texlive to be installed for tectonic to work; the tool download everything it needs from the Internet. I do not know how secure the process is.
3. Tho tool itself is easy to use: `tectonic main.tex` just works. I didn’t tried with third-party packages though.
4. By default, the tool cleans the directory when it has finished, deals with `bibtex` etc. (didn't tried that one) a little like `latexmk` does.
5. By default, it checks if new versions of its `tex` packages are available and I didn't find a way to tell it not to do it (because I had a poor Internet connection at the time and it was taken some time)

However, the tool does not support `eps` images (with `graphicx` package) so I couldn’t use it for the beamer presentation I was working on.

**Comment by pierre-24** [comment]
~~It is because of Rust, confess :p~~

Why not. I will do like @lethom, I will test on my own LaTeX codes and see what it does :)

**Comment by vhf** [comment]
I don't care if it's Rust, Java or PHP tbh but I really dislike the way we usually have to use LaTeX. :)

In our context, the LaTeX compiler stopping mid-way to ask questions, generating thousand of log lines, having to deal with a bunch of temporary files, these are issues that this tool seems to take care of.

**Comment by pierre-24** [comment]
> In our context, the LaTeX compiler stopping mid-way to ask questions

That part is not true if you use `-interaction=nonstopmode`.

>  generating thousand of log lines,

So does the tools, it just cleans at the end :p 

> having to deal with a bunch of temporary files

Well, once again ... So does the tools, it just cleans at the end :-° (note that those temporary files are most of the time not created by LaTeX himself, but external packages, for example `glosssaries` or `bibtex`, and I doubt that those packages are reimplemented).

-------

This seems like a very useful and clean tool (better that a very complex makefile), but don't oversell it :p  

 By the way, we will have to check if `-shell-escape` is supported with this tools (since this is needed by minted).

**Comment by AmarOk1412** [comment]
Ooh! Awesome.

I just tried with the template and it doesn't work because of https://github.com/tectonic-typesetting/tectonic/issues/37 so we should wait for v0.1.6 and retry.

**Comment by lethom** [comment]
That’s the issue with new *promising* projects; they look so good you want to use them and they dare not to be ready!

**Comment by pierre-24** [comment]
Well, https://github.com/tectonic-typesetting/tectonic/issues/38 is, for now, the main reason that we cannot adopt this project: on the basis that "tectonic should run standalone", the owner does not want `-shell-escape` to be implemented (which we need for `minted`). Also, right now, it does not support the "common" images formats, see https://github.com/tectonic-typesetting/tectonic/issues/78. It is kinda painful (I'm a heavy consumer of eps and png images, so none of my personal document did compile, and so does the template, even when I trick the code by using the English babel). 

I agree on the spirit, but like @lethom said, it is not ready. At all.
