### ISSUE TITLE
Failing real life example

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/latex-template#73]
Hi guys,

I tried to generate a pdf of one of my tutorial.
To do so, I made a fresh install in a virtual machine to test everything. I installed a clean zds-site (branch zmarkdown-notes) and fetch the template. Anyhow, after few things, I managed to get it compiling...almost. I have a ton of error and latex just give up after 100 of them.

Here is a gist with the md/tex/log data

https://gist.github.com/Eskimon/1a0c9751f84b85186119a33c0ed964e8

**Comment by pierre-24** [comment]
Thanks for this nice example ;)

There is actually 3 things that are "wrong" in that document:

+ Since the recent improvement of @Heziode, the syntax of `\licence` has changed, and I guess that it is not up to date in the parser, but it is probably us that should mention that ^^
+ The images. Obviously, they are not provided here, but anyway there is another bug that I mention in https://github.com/zestedesavoir/zmarkdown/issues/137 (but since there were many bugs mentioned, so I'll resignal it :p )
+ Finally, there is something that rebber does with the youtube video: it transforms the `!(youtube.com/xxx)` into an image ... But use the url to this image directly in LaTeX, which does not knows how to fetch urls (yeah, LaTeX is an old language :p ).

I'll open an issue into zmarkdown repo, but thanks for trying :)

**Comment by artragis** [comment]
For licence => zmd is still not released @sandhose 

for youtube/rebber it's known and not so simple to fix

for the extension issue, It's a zds issue I think (or a latex issue). Perhaps as we now use lua you can perform some "temp file operation" when you detect more than one dot?

**Comment by pierre-24** [comment]
I like your idea for the third point, if I find some time, I'll look in that direction :)

**Comment by artragis** [comment]
https://github.com/zestedesavoir/zds-site/pull/4733 is updated to fix the licence issue.

you need to install zmd at its newest version & manualy add lua external dependency to make it work but it's ok.

**Comment by pierre-24** [comment]
Ok, nice :)

I have a few piece of code to mix together in order to fix the "multiple dot" issue, but I think I will be able to make that one right. For Youtube, communicating trough http(s) in lua seems ... Difficult, so it is on you :p

**Comment by artragis** [comment]
an update https://gist.github.com/artragis/b89957c58aef1f437111836df693bebe

nota : printable is built.

**Comment by artragis** [comment]
The error seems to be generated by an `\externalLink` inside a `\image` caption. Once I removed it, the pdf was produced properly
[developper-et-publier-une-app-android-material-design.pdf](https://github.com/zestedesavoir/latex-template/files/1606571/developper-et-publier-une-app-android-material-design.pdf)

**Comment by pierre-24** [comment]
I think we are done here ;)

(until next time)
